<<<<<<< HEAD
avatar_2:
 preparation: False
 bbox_shift: -2
 batch_size: 6  # Reduce from 4 to 2
 video_path: "data/video/sun.mp4"
 audio_clips:
     audio_0: "data/audio/sun.wav"
     audio_1: "data/audio/yongen.wav"
=======
avator_1:
 preparation: True # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 5
 video_path: "data/video/yongen.mp4"
 audio_clips:
     audio_0: "data/audio/yongen.wav"
     audio_1: "data/audio/eng.wav"
 
  

>>>>>>> main
