avatar_2:
 preparation: False
 bbox_shift: 0
 batch_size: 8  # Reduce from 4 to 2
 video_path: "data/video/sun.mp4"
 audio_clips:
     audio_0: "data/audio/sun.wav"
     audio_1: "data/audio/yongen.wav"
